### ISSUE TITLE
[node-0.4] AttributeError: 'NoneType' object has no attribute 'copy'

### ISSUE THREAD

**Issue by strk** [kkaefer/node-zlib#9]
Is there any version which works with node-0.4 ?
